### ISSUE TITLE
More than one line break are inserted

### ISSUE THREAD

**Issue by wataridori** [wataridori/chatpp#10]
Khi gõ tên ai đó, và dùng phím arrow xuống để chọn tên người thì thỉnh thoảng có xảy ra trường hợp có nhiều dấu xuống dòng.
![chatpperror](http://i.gyazo.com/f530f51829a762adb1937ff5a35c72b3.gif)

**Comment by nguyenvanvuong** [comment]
@wataridori Anh dùng soft gì để tạo ra cái ảnh gif kia thế ?

**Comment by wataridori** [comment]
@nguyenvanvuong 
Gyazo GIF 
https://gyazo.com/
