### ISSUE TITLE
Cannot add new Emo data

### ISSUE THREAD

**Issue by b1acKr0se** [wataridori/chatpp#95]
When adding a new emo link (a valid one, such as the "Vietnamese" package) an error dialog is shown with this message:

```
Invalid URL! Make sure your inputted URL is correct, and a Dropbox link!
```

Experienced on Chrome 73.0.3683.75, MacOS 10.13.4.

**Comment by wataridori** [comment]
@b1acKr0se This problem has been fixed in the 5.3.1 Update. 

Thank you very much for the notice 👍
